function modelFile = build_cartpole_model()
%BUILD_CARTPOLE_MODEL Rebuild the canonical SLX from the untouched template.
% The controller is inserted through MATLAB's Stateflow API so the SLX
% metadata is generated by MATLAB rather than edited as raw XML.

projectRoot = fileparts(mfilename('fullpath'));
templateFile = fullfile(projectRoot,'template','cartpole.slx');
controllerFile = fullfile(projectRoot,'controller_block.m');
modelFile = fullfile(projectRoot,'cartpole.slx');
temporaryDir = fullfile(projectRoot,'tmp','rebuilt_cartpole');
temporaryFile = fullfile(temporaryDir,'cartpole.slx');

if ~isfile(templateFile)
    error('CartPole:MissingTemplate','Missing template model: %s',templateFile);
end
if ~isfile(controllerFile)
    error('CartPole:MissingController','Missing controller source: %s',controllerFile);
end
if ~isfolder(temporaryDir)
    mkdir(temporaryDir);
end

bdclose('all');
load_system(templateFile);
modelName = 'cartpole';

root = sfroot;
chart = root.find('-isa','Stateflow.EMChart', ...
    'Path',[modelName '/MATLAB Function']);
if isempty(chart) || numel(chart) ~= 1
    bdclose(modelName);
    error('CartPole:ControllerBlock', ...
        'Expected one MATLAB Function block at cartpole/MATLAB Function.');
end

% The template already defines the original arguments as parameters. Add
% the empirical capture-zone parameters using the supported object API.
parameterNames = {'P_lqr','c_cap'};
for parameterIndex = 1:numel(parameterNames)
    name = parameterNames{parameterIndex};
    data = chart.find('-isa','Stateflow.Data','Name',name);
    if isempty(data)
        data = Stateflow.Data(chart);
        data.Name = name;
    end
    data.Scope = 'Parameter';
end

chart.Script = fileread(controllerFile);
% Interactive desktop runs should open the 3-D cart-pole animation in
% Multibody Explorer. Headless runs can still turn this off through the
% setup_cartpole option without changing the saved model.
set_param(modelName,'SimMechanicsOpenEditorOnUpdate','on');

% Store one complete, validated swing-up design in the model workspace.
% This makes the SLX runnable directly from its Run button without relying
% on variables left in the MATLAB base workspace. setup_cartpole overrides
% these values temporarily when it runs a newly optimized experiment.
defaultResult = setup_cartpole(struct( ...
    'runSimulink',false, ...
    'makePlots',false, ...
    'verbose',false, ...
    'runCaptureStudy',false));
defaultNames = {'param','Ts','Fmax','K_lqr','Knom','Unom','Xnom', ...
    'P_lqr','c_cap'};
defaultValues = {defaultResult.parameters,defaultResult.Ts, ...
    defaultResult.Fmax,defaultResult.K_lqr,defaultResult.Knom, ...
    defaultResult.Unom,defaultResult.Xnom,defaultResult.P_lqr, ...
    defaultResult.c_cap};
modelWorkspace = get_param(modelName,'ModelWorkspace');
for defaultIndex = 1:numel(defaultNames)
    assignin(modelWorkspace,defaultNames{defaultIndex}, ...
        defaultValues{defaultIndex});
end
set_param(modelName,'StopTime','8');
save_system(modelName,temporaryFile);
bdclose(modelName);

% Prove that the freshly serialized Stateflow section can be loaded before
% replacing the canonical model. This specifically guards against a broken
% or hand-edited chart inside an SLX archive.
load_system(temporaryFile);
bdclose(modelName);
copyfile(temporaryFile,modelFile,'f');
load_system(modelFile);
bdclose(modelName);

fprintf('Rebuilt and load-tested %s\n',modelFile);
end
